function iso(y, m, d) {
  return new Date(Date.UTC(y, m - 1, d)).toISOString().slice(0, 10);
}

export function defaultState() {
  return {
    project: "Glaz",
    tasks: [
      {
        id: "t1",
        title: "Personalizar este quadro para o Projeto Glaz",
        description: "Troque estes exemplos pelas tarefas reais do projeto.",
        status: "todo",
        priority: "baixa",
        assignee: null,
        dueDate: null,
        tags: ["Configuração"],
        subtasks: [
          { text: "Adicionar as primeiras tarefas reais", done: false },
          { text: "Remover os cartões de exemplo", done: false },
        ],
        createdAt: iso(2026, 8, 18),
        updatedAt: iso(2026, 8, 18),
      },
      {
        id: "t2",
        title: "Cotar fornecedores para o próximo lote",
        description: "",
        status: "todo",
        priority: "media",
        assignee: "cassius",
        dueDate: iso(2026, 9, 6),
        tags: ["Compras"],
        subtasks: [],
        createdAt: iso(2026, 8, 20),
        updatedAt: iso(2026, 8, 20),
      },
      {
        id: "t3",
        title: "Organizar reunião mensal de resultados",
        description: "",
        status: "todo",
        priority: "baixa",
        assignee: "rafael",
        dueDate: iso(2026, 9, 10),
        tags: ["Gestão"],
        subtasks: [],
        createdAt: iso(2026, 8, 21),
        updatedAt: iso(2026, 8, 21),
      },
      {
        id: "t4",
        title: "Fechar proposta com cliente novo",
        description: "Enviar contrato revisado e alinhar prazo de entrega.",
        status: "doing",
        priority: "alta",
        assignee: "rafael",
        dueDate: iso(2026, 9, 2),
        tags: ["Vendas", "Cliente"],
        subtasks: [
          { text: "Revisar valores", done: true },
          { text: "Enviar contrato", done: false },
        ],
        createdAt: iso(2026, 8, 22),
        updatedAt: iso(2026, 8, 29),
      },
      {
        id: "t5",
        title: "Atualizar planilha financeira do mês",
        description: "",
        status: "doing",
        priority: "media",
        assignee: "cassius",
        dueDate: iso(2026, 9, 1),
        tags: ["Financeiro"],
        subtasks: [],
        createdAt: iso(2026, 8, 23),
        updatedAt: iso(2026, 8, 28),
      },
      {
        id: "t6",
        title: "Revisar contrato de prestação de serviço",
        description: "Confirmar cláusula de rescisão com o cliente antes de assinar.",
        status: "review",
        priority: "alta",
        assignee: "cassius",
        dueDate: iso(2026, 8, 30),
        tags: ["Jurídico"],
        subtasks: [],
        createdAt: iso(2026, 8, 15),
        updatedAt: iso(2026, 8, 30),
      },
      {
        id: "t7",
        title: "Abrir conta PJ do Projeto Glaz",
        description: "",
        status: "done",
        priority: "alta",
        assignee: "rafael",
        dueDate: iso(2026, 8, 11),
        tags: ["Financeiro"],
        subtasks: [],
        createdAt: iso(2026, 8, 1),
        updatedAt: iso(2026, 8, 11),
      },
      {
        id: "t8",
        title: "Definir identidade visual inicial",
        description: "",
        status: "done",
        priority: "media",
        assignee: "cassius",
        dueDate: iso(2026, 8, 21),
        tags: ["Marketing"],
        subtasks: [],
        createdAt: iso(2026, 8, 5),
        updatedAt: iso(2026, 8, 21),
      },
    ],
    activity: [
      { ts: "2026-08-30T14:00:00.000Z", who: "cassius", text: 'moveu "Revisar contrato de prestação de serviço" para Em Revisão' },
      { ts: "2026-08-29T10:00:00.000Z", who: "rafael", text: 'criou "Fechar proposta com cliente novo"' },
      { ts: "2026-08-25T09:00:00.000Z", who: "rafael", text: 'concluiu "Abrir conta PJ do Projeto Glaz"' },
      { ts: "2026-08-21T16:00:00.000Z", who: "cassius", text: 'concluiu "Definir identidade visual inicial"' },
    ],
  };
}
